export { Agent, runAgent } from './agent.js';
export type { AgentOptions } from './agent.js';
export { LLMClient } from './llm.js';
export type { LLMConfig } from './llm.js';
export { ConversationMemory } from './memory.js';
export type { Message, ToolCall } from './memory.js';
export { loadConfig } from './config.js';
export type { SparkConfig } from './config.js';
export { ToolRegistry, createToolRegistry } from './tools/index.js';
export type { Tool } from './tools/index.js';
export { SafetyChecker, requiresConfirmation } from './safety.js';
export { TaskPlanner } from './task-planner.js';
export type { TodoItem, TaskStatus, CheckpointSnapshot } from './task-planner.js';
export { estimateTokens, estimateMessagesTokens, truncateToolResult } from './token-counter.js';
export { buildDynamicSystemPrompt, buildProjectContext } from './prompt.js';
export { FileBackupManager } from './undo-manager.js';
export { TokenTracker } from './token-tracker.js';
export type { TokenUsage, TokenReport } from './token-tracker.js';
export { getCheckpointsDir } from './config.js';
